### ISSUE TITLE
Criar RestController para listagem de um cliente em service

### ISSUE THREAD

**Issue by Bianca-goncalvess** [Bianca-goncalvess/helpr-1#1]
- [x]  Criar um controlador Rest
- [x]  Criar serviço de cliente
- [x]  Criar metodo para Endpoint de RestController
- [x] Vincular os repositorios de cliente
- [x] Listar Endpoint no Postman

**Comment by soulcode-acad** [comment]
Bianca deu show em, sobre o código esta legal demais bem feito! Parabéns ... tem um pouco de sujeira de código e redundância cuidado para não confundir futuros Devs. Faltou etiquetar as entregas e cartões para facilitar a vida do revisor.  De resto estava muito bom e deu show grato pela evolução!

![image](https://user-images.githubusercontent.com/100297907/172922262-38368ad2-82a6-4090-ac92-ea122002d18b.png)
